apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secret
  namespace: url-shortener
type: Opaque
data:
  # Значення має бути закодоване у Base64.
  # echo -n "postgresql://shortener:secret@db:5432/shortener_db" | base64
  DATABASE_URL: cG9zdGdyZXNxbDovL3Nob3J0ZW5lcjpzZWNyZXRAZGI6NTQzMi9zaG9ydGVuZXJfZGI=